---
- hosts: ubuntuserver
  gather_facts: False
  tasks:
    
    - name: Change Operator List
      blockinfile:
        path: /dg/operator.lst
        state: present
        backup: true
        block: "{{ block }}"

    - debug: msg= "{{ lookup('pipe','date') }}"
