---
- hosts: ubuntuserver
  gather_facts: False
  tasks:
    
    - name: Change Operator List
      lineinfile:
        path: /dg/operator.lst
        state: present
        backup: true
        line: "{{ line }}"

    - debug: msg= "{{ lookup('pipe','date') }}"
